// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "util/inv_application.h"
#include "UfsServiceHandler.h"
// #include <signal.h>


int main(int argc, char **argv) {

    INIT_INV_LOGGER("INV", "UfsService");

    g_pool = new ThreadPool(8);
    INVApplication<UfsServiceHandler, UfsServiceProcessor> application;
    application.start(argc, argv);

    return 0;
}
