package com.inveno.ser;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsListRespPro.proto

public final class NewsListRespPro {
  private NewsListRespPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewsListRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 retcode = 1;
    /**
     * <code>required int32 retcode = 1;</code>
     */
    boolean hasRetcode();
    /**
     * <code>required int32 retcode = 1;</code>
     */
    int getRetcode();

    // repeated .ResponParam data = 2;
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    java.util.List<ResponDataPro.ResponParam> 
        getDataList();
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    ResponDataPro.ResponParam getData(int index);
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    java.util.List<? extends ResponDataPro.ResponParamOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    ResponDataPro.ResponParamOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NewsListResp}
   */
  public static final class NewsListResp extends
      com.google.protobuf.GeneratedMessage
      implements NewsListRespOrBuilder {
    // Use NewsListResp.newBuilder() to construct.
    private NewsListResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NewsListResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NewsListResp defaultInstance;
    public static NewsListResp getDefaultInstance() {
      return defaultInstance;
    }

    public NewsListResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NewsListResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              retcode_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                data_ = new java.util.ArrayList<ResponDataPro.ResponParam>();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(input.readMessage(ResponDataPro.ResponParam.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NewsListRespPro.internal_static_NewsListResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NewsListRespPro.internal_static_NewsListResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NewsListRespPro.NewsListResp.class, NewsListRespPro.NewsListResp.Builder.class);
    }

    public static com.google.protobuf.Parser<NewsListResp> PARSER =
        new com.google.protobuf.AbstractParser<NewsListResp>() {
      public NewsListResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewsListResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NewsListResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 retcode = 1;
    public static final int RETCODE_FIELD_NUMBER = 1;
    private int retcode_;
    /**
     * <code>required int32 retcode = 1;</code>
     */
    public boolean hasRetcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 retcode = 1;</code>
     */
    public int getRetcode() {
      return retcode_;
    }

    // repeated .ResponParam data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<ResponDataPro.ResponParam> data_;
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    public java.util.List<ResponDataPro.ResponParam> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    public java.util.List<? extends ResponDataPro.ResponParamOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    public ResponDataPro.ResponParam getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .ResponParam data = 2;</code>
     */
    public ResponDataPro.ResponParamOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      retcode_ = 0;
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRetcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, retcode_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(2, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retcode_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NewsListRespPro.NewsListResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NewsListRespPro.NewsListResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NewsListRespPro.NewsListResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NewsListRespPro.NewsListResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NewsListRespPro.NewsListResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NewsListRespPro.NewsListResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NewsListRespPro.NewsListResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NewsListRespPro.NewsListResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NewsListRespPro.NewsListResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NewsListRespPro.NewsListResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NewsListRespPro.NewsListResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewsListResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NewsListRespPro.NewsListRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NewsListRespPro.internal_static_NewsListResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NewsListRespPro.internal_static_NewsListResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NewsListRespPro.NewsListResp.class, NewsListRespPro.NewsListResp.Builder.class);
      }

      // Construct using NewsListRespPro.NewsListResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        retcode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NewsListRespPro.internal_static_NewsListResp_descriptor;
      }

      public NewsListRespPro.NewsListResp getDefaultInstanceForType() {
        return NewsListRespPro.NewsListResp.getDefaultInstance();
      }

      public NewsListRespPro.NewsListResp build() {
        NewsListRespPro.NewsListResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NewsListRespPro.NewsListResp buildPartial() {
        NewsListRespPro.NewsListResp result = new NewsListRespPro.NewsListResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retcode_ = retcode_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NewsListRespPro.NewsListResp) {
          return mergeFrom((NewsListRespPro.NewsListResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NewsListRespPro.NewsListResp other) {
        if (other == NewsListRespPro.NewsListResp.getDefaultInstance()) return this;
        if (other.hasRetcode()) {
          setRetcode(other.getRetcode());
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRetcode()) {
          
          return false;
        }
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NewsListRespPro.NewsListResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NewsListRespPro.NewsListResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 retcode = 1;
      private int retcode_ ;
      /**
       * <code>required int32 retcode = 1;</code>
       */
      public boolean hasRetcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 retcode = 1;</code>
       */
      public int getRetcode() {
        return retcode_;
      }
      /**
       * <code>required int32 retcode = 1;</code>
       */
      public Builder setRetcode(int value) {
        bitField0_ |= 0x00000001;
        retcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 retcode = 1;</code>
       */
      public Builder clearRetcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retcode_ = 0;
        onChanged();
        return this;
      }

      // repeated .ResponParam data = 2;
      private java.util.List<ResponDataPro.ResponParam> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<ResponDataPro.ResponParam>(data_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ResponDataPro.ResponParam, ResponDataPro.ResponParam.Builder, ResponDataPro.ResponParamOrBuilder> dataBuilder_;

      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public java.util.List<ResponDataPro.ResponParam> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public ResponDataPro.ResponParam getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public Builder setData(
          int index, ResponDataPro.ResponParam value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public Builder setData(
          int index, ResponDataPro.ResponParam.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public Builder addData(ResponDataPro.ResponParam value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public Builder addData(
          int index, ResponDataPro.ResponParam value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public Builder addData(
          ResponDataPro.ResponParam.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public Builder addData(
          int index, ResponDataPro.ResponParam.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends ResponDataPro.ResponParam> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public ResponDataPro.ResponParam.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public ResponDataPro.ResponParamOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public java.util.List<? extends ResponDataPro.ResponParamOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public ResponDataPro.ResponParam.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            ResponDataPro.ResponParam.getDefaultInstance());
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public ResponDataPro.ResponParam.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, ResponDataPro.ResponParam.getDefaultInstance());
      }
      /**
       * <code>repeated .ResponParam data = 2;</code>
       */
      public java.util.List<ResponDataPro.ResponParam.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ResponDataPro.ResponParam, ResponDataPro.ResponParam.Builder, ResponDataPro.ResponParamOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ResponDataPro.ResponParam, ResponDataPro.ResponParam.Builder, ResponDataPro.ResponParamOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NewsListResp)
    }

    static {
      defaultInstance = new NewsListResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewsListResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NewsListResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewsListResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025NewsListRespPro.proto\032\021ResponDataPro.pro" +
      "to\";\n\014NewsListResp\022\017\n\007retcode\030\001 \002(\005\022\032\n\004d" +
      "ata\030\002 \003(\0132\014.ResponParam"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NewsListResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NewsListResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NewsListResp_descriptor,
              new java.lang.String[] { "Retcode", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ResponDataPro.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
